### ISSUE TITLE
createPayment error

### ISSUE THREAD

**Issue by dbergan** [veeminc/veem-php-sdk#4]
Hi,

I'm at the developer sandbox trying to get createPayment to work. I'm using your page here:

https://developer.veem.com/reference/createpaymentusingpost_1

Here's my request:
curl --request POST
--url https://sandbox-api.veem.com/veem/v1.1/payments
--header 'Accept: application/json'
--header 'Authorization: Bearer b24dc903-5ea0-4dc1-bfe0-91eaed583d36'
--header 'Content-Type: application/json'
--data '
{
"amount": {
"currency": "USD",
"number": 1000
},
"payee": {
"businessName": "Shivan Eyecare",
"countryCode": "US",
"email": "shivan2@optilegra.com",
"firstName": "Shivan",
"lastName": "Dragon",
"type": "Business",
"phone": "18193180000"
},
"purposeOfPayment": "Vision Claims"
}
'

Here's the response:
{
"code": 50000000,
"message": "Value is unexpected: 11089",
"timestamp": "2021-11-17T22:46:23.570",
"fileName": "VeemResponseHandler.java",
"lineNumber": 89
}

The value "11089" is the customer ID for "Shivan Eyecare". (set up in my Dev Dashboard Sandbox)

My curl is simply following the example. What am I doing wrong?

Kind regards,
David

**Comment by ralfdagher** [comment]
Hi David

The issue is that the token you are using is for the same account you are
sending the payment to. Effectively you are sending a payment to yourself
and that is why it is failing. Either change the token or change the payee
email.

Regards,
Ralf

**Comment by dbergan** [comment]
Aha, ok. Thanks for the quick reply.
